apiVersion: v1
kind: Service
metadata:
  labels:
    app: nginx
  name: nginx
  namespace: default
spec:
  ports:
    - port: 81
      protocol: TCP
      targetPort: 81
  selector:
    app: nginx
  type: ClusterIP

