apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 81  # Esta é a porta exposta pelo serviço dentro do cluster
      targetPort: 81  # Esta é a porta do container
  type: ClusterIP

